version: '3.2'
services:
  redis:
    image: redis:alpine
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - ./data/redis:/data
    container_name: todobot_redis
  mongo:
    image: mongo:latest
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - ./data/mongo:/data/db
    container_name: todobot_mongo
  apm-server:
    build:
      context: packages/DOCKER/apm-server/
      args:
        ELK_VERSION: 7.11.1
    command:
      # Disable strict permission checking on 'apm-server.yml' configuration file
      # https://www.elastic.co/guide/en/beats/libbeat/current/config-file-permissions.html
      - --strict.perms=false
    volumes:
      - type: bind
        source: ./packages/DOCKER/apm-server/config/apm-server.yml
        target: /usr/share/apm-server/apm-server.yml
        read_only: true
    ports:
      - '127.0.0.1:8200:8200'
