name: "Generate Docs"

on:
  push:
    branches:
      - "master"

jobs:
  docgen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install DOCGEN Packages
        run: "cd packages/DOCGEN && npm install"
      - name: Install TODOBOT Packages
        run: "cd packages/TODOBOT && npm install --no-optional"
      - name: Compile TODOBOT
        run: "cd packages/TODOBOT && npm run build"
      - name: Generate Docs
        run: "cd packages/DOCGEN && npm run gen"
      - name: Install Frontend Packages
        run: "cd packages/FRONTEND && npm install"
      - name: Build Frontend
        run: "cd packages/FRONTEND && npm run build:prod"
      - name: Commit and push Changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git diff --staged --quiet || git commit -m "ci (build | docs): generate docs for $GITHUB_SHA"
          git push --all
